---
DirectoryPath: build/site/che-7 # Not build/site to avoid false positives on 404.html
IgnoreInternalEmptyHash: true # Legit empty hash present in every page
OutputDir: .cache/htmltest
CacheExpires: "6h" # Default is 2 weeks.
IgnoreURLs:
  - https://cse.google.com/cse.js
  - https://marketplace.visualstudio.com
