apiVersion: che.eclipse.org/v1alpha1
kind: {image-puller-cr-name}
metadata:
  name: image-puller
  namespace: <namespace you installed the image puller in>
spec:
  configMapName: {image-puller-deployment-name}
  daemonsetName: {image-puller-deployment-name}
  deploymentName: {image-puller-deployment-name}
  images: >-
    java11-maven=quay.io/eclipse/che-java11-maven:nightly;che-theia=quay.io/eclipse/che-theia:next
