#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# GitHub Actions configuration file for htmltest
# See: https://github.com/wjdp/htmltest

name: linkchecker-pr-check

on:
  workflow_run:
    workflows: ["build-documentation-pr"]
    types:
      - completed

jobs:
  linkchecker:
    name: link checker
    runs-on: ubuntu-20.04
    container: "quay.io/eclipse/che-docs:latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache htmltest status code of checked external URLs # See: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
        uses: actions/cache@v2
        env:
          cache-name: cache-htmltest
        with:
          key: refcache.json
          path: .cache/htmltest

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: doc-content

      - name: Check internal and external links using htmltest
        id: validate-links
        run: htmltest
